version: "3.9"
services:
  frontend:
    image: my-forum-frontend:latest
    ports:
      - "3000:80"
  backend:
    environment:
      - SECRET_DB_LINK=mongodb+srv://kemplail:*WJ2sB@cluster0.rfu85.mongodb.net/my-forum?retryWrites=true&w=majority
    image: "my-forum-backend:latest"
    ports:
      - "5000:5000"
