version: '3'

networks:
  monitor-net:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - monitor-net
      
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - '/:/rootfs'
      - '/var/run:/var/run'
      - '/sys:/sys'
      - '/var/lib/docker/:/var/lib/docker'
      - '/dev/disk/:/dev/disk'
    ports: 
      - 8080:8080
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:7.3.6
    ports:
      - 2000:3000
    networks:
      - monitor-net