global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090'] ## IP Address of the localhost

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          alias: 'cadvisor'