apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-volume
  labels:
    purpose: grafana
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/working/grafana-volume/grafana"